#!/bin/bash


EXE_NAME=bowlerstudio
SCRIPT_EXPECTED=$HOME/bin/$EXE_NAME

DESKTOP_FILE=$HOME/bin/bowlerstudio.desktop
 
SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

#https://cdn.azul.com/zulu/bin/zulu8.62.0.19-ca-fx-jdk8.0.332-macosx_x64.zip
JVERELEASE=zulu8.62.0.19-ca-fx-jdk8.0.332-macosx_x64
JVMDIR=$HOME/bin/java8/
JAR=BowlerStudio.jar
AUTOUPDATE=$HOME/bin/java8/LatestFromGithubLaunch.jar

unzipifiy(){
	testget  $1 $2
	echo "Unzipping $1 to $2"
	tar -xzf $2/$1.tar.gz -C $2
	mv $2/$1/* $2/
	rmdir $2/$1/
}

testget () {
	if [ -f $JVERELEASE.tar.gz ]; then
		echo "$JVERELEASE.tar.gz exist"
		else
		echo Downloading from https://www.azul.com/downloads/zulu/zulufx/ 
		echo downloading https://cdn.azul.com/zulu/bin/$JVERELEASE.tar.gz
		curl -L https://cdn.azul.com/zulu/bin/$JVERELEASE.tar.gz  -o $2$1.tar.gz
	fi
}

if (! test -e $JVMDIR/$JVERELEASE.tar.gz) then
	rm -rf $JVMDIR
	mkdir -p $JVMDIR
	unzipifiy $JVERELEASE $JVMDIR
fi
if (! test -e $AUTOUPDATE) then
	curl -L https://github.com/CommonWealthRobotics/LatestFromGithubLaunch/releases/latest/download/LatestFromGithubLaunch.jar -o $AUTOUPDATE
fi


# Copy the script to $HOME/bin if it is not already there
if ! [ "$SCRIPT" = "$HOME/bin" ]; then
 echo "Script source copied to $HOME/bin from " $SCRIPT
 cp $SCRIPT/$EXE_NAME $SCRIPT_EXPECTED
 chmod +x  $SCRIPT_EXPECTED
fi

set -e
if grep -q '$HOME/bin/' $HOME/.bashrc; then 
	echo "Skipping adding ~/bin/ to $HOME/.bashrc, command already exists"; 
else 
	echo 'export PATH=$PATH:$HOME/bin/'  >> $HOME/.bashrc; 
	echo 'echo Path: $PATH'  >> $HOME/.bashrc; 
	echo 'Added $PATH=$PATH:$HOME/bin/ to ~/.bashrc'; 
	source  $HOME/.bashrc
fi
source  $HOME/.bashrc

$JVMDIR/bin/java -jar $AUTOUPDATE CommonWealthRobotics BowlerStudio BowlerStudio.jar $JVMDIR/bin/java -Dprism.forceGPU=true -jar 
