#!/bin/bash


EXE_NAME=bowlerstudio
SCRIPT_EXPECTED=$HOME/bin/$EXE_NAME

DESKTOP_FILE=$HOME/bin/bowlerstudio.desktop
 
SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ICON=$HOME/bin/splash.png

if (! test -e $DESKTOP_FILE) then
	echo "[Desktop Entry]
	Version=1.0
	Type=Application
	Name=BowlerStudio
	Comment=BowlerStudio Robotics IDE
	Exec=$SCRIPT_EXPECTED
	Icon=$ICON
	Path=
	Terminal=false
	StartupNotify=false" > $DESKTOP_FILE
	chmod +x $DESKTOP_FILE
	gio set $DESKTOP_FILE "metadata::trusted" yes
	sudo desktop-file-install $DESKTOP_FILE
fi

#https://cdn.azul.com/zulu/bin/zulu8.42.0.23-ca-fx-jre8.0.232-linux_x64.tar.gz
JVERELEASE=zulu8.44.0.13-ca-fx-jdk8.0.242-linux_x64
#JVERELEASE=zulu8.42.0.23-ca-fx-jre8.0.232-linux_x64
JVMDIR=$HOME/bin/java8/
JAR=BowlerStudio.jar
AUTOUPDATE=$HOME/bin/java8/LatestFromGithubLaunch.jar

unzipifiy(){
	testget  $1 $2
	echo "Unzipping $1 to $2"
	tar -xzf $2/$1.tar.gz -C $2
	mv $2/$1/* $2/
	rmdir $2/$1/
}

testget () {
	if [ -f $JVERELEASE.tar.gz ]; then
		echo "$JVERELEASE.tar.gz exist"
		else
		echo Downloading from https://www.azul.com/downloads/zulu/zulufx/ 
		echo downloading https://cdn.azul.com/zulu/bin/$JVERELEASE.tar.gz
		wget https://cdn.azul.com/zulu/bin/$JVERELEASE.tar.gz  -O $2$1.tar.gz
	fi
}

if (! test -e $JVMDIR/$JVERELEASE.tar.gz) then
	rm -rf $JVMDIR
	mkdir -p $JVMDIR
	unzipifiy $JVERELEASE $JVMDIR
fi
if (! test -e $AUTOUPDATE) then
	wget https://github.com/CommonWealthRobotics/LatestFromGithubLaunch/releases/latest/download/LatestFromGithubLaunch.jar -O $AUTOUPDATE
fi


# Copy the script to $HOME/bin if it is not already there
if ! [ "$SCRIPT" = "$HOME/bin" ]; then
 echo "Script source copied to $HOME/bin from " $SCRIPT
 cp $SCRIPT/$EXE_NAME $SCRIPT_EXPECTED
 chmod +x  $SCRIPT_EXPECTED
fi

if (! test -e $ICON) then
	wget https://github.com/madhephaestus/Installer-Linux-BowlerStudio/releases/latest/download/splash.png -O $ICON
fi
set -e
if grep -q '$HOME/bin/' $HOME/.bashrc; then 
	echo "Skipping adding ~/bin/ to $HOME/.bashrc, command already exists"; 
else 
	echo 'export PATH=$PATH:$HOME/bin/'  >> $HOME/.bashrc; 
	echo 'echo Path: $PATH'  >> $HOME/.bashrc; 
	echo 'Added $PATH=$PATH:$HOME/bin/ to ~/.bashrc'; 
	source  $HOME/.bashrc
fi
source  $HOME/.bashrc

$JVMDIR/bin/java -jar $AUTOUPDATE CommonWealthRobotics BowlerStudio BowlerStudio.jar $JVMDIR/bin/java -Dprism.forceGPU=true -jar 
